INSERT INTO g5_config SET 
cf_title = '그누보드5',
cf_theme = 'basic',
cf_admin = 'admin',
cf_admin_email = 'admin@domain.com',
cf_admin_email_name = '그누보드5',
cf_use_point = '1',
cf_use_copy_log = '1',
cf_login_point = '100',
cf_memo_send_point = '500',
cf_cut_name = '15',
cf_nick_modify = '60',
cf_new_skin = 'basic',
cf_new_rows = '15',
cf_search_skin = 'basic',
cf_connect_skin = 'basic',
cf_faq_skin = 'basic',
cf_read_point = '0',
cf_write_point = '0',
cf_comment_point = '0',
cf_download_point = '0',
cf_write_pages = '10',
cf_mobile_pages = '5',
cf_link_target = '_blank',
cf_delay_sec = '30',
cf_filter = '',
cf_possible_ip = '',
cf_intercept_ip = '',
cf_analytics = '',
cf_member_skin = 'basic',
cf_mobile_new_skin = 'basic',
cf_mobile_search_skin = 'basic',
cf_mobile_connect_skin = 'basic',
cf_mobile_member_skin = 'basic',
cf_mobile_faq_skin = 'basic',
cf_editor = 'smarteditor2',
cf_captcha_mp3 = 'basic',
cf_register_level = '2',
cf_register_point = '1000',
cf_icon_level = '2',
cf_leave_day = '30',
cf_search_part = '10000',
cf_email_use = '1',
cf_prohibit_id = 'admin,administrator,관리자',
cf_prohibit_email = '',
cf_new_del = '30',
cf_memo_del = '180',
cf_visit_del = '180',
cf_popular_del = '180',
cf_use_member_icon = '2',
cf_member_icon_size = '5000',
cf_member_icon_width = '22',
cf_member_icon_height = '22',
cf_member_img_size = '50000',
cf_member_img_width = '60',
cf_member_img_height = '60',
cf_login_minutes = '10',
cf_image_extension = 'gif|jpg|jpeg|png',
cf_flash_extension = 'swf',
cf_movie_extension = 'asx|asf|wmv|wma|mpg|mpeg|mov|avi|mp3',
cf_formmail_is_member = '1',
cf_page_rows = '15',
cf_mobile_page_rows = '15',
cf_cert_limit = '2',
cf_stipulation = '회원가입약관',
cf_privacy = '개인정보처리방침',
cf_open_modify = '0';

INSERT INTO g5_qa_config (qa_title, qa_category, qa_skin, qa_mobile_skin, qa_use_email, qa_req_email, qa_use_hp, qa_req_hp, qa_use_editor, qa_subject_len, qa_mobile_subject_len, qa_page_rows, qa_mobile_page_rows, qa_image_width, qa_upload_size, qa_insert_content) 
VALUES ('1:1문의', '회원|포인트', 'basic', 'basic', '1', '0', '1', '0', '1', '60', '30', '15', '15', '600', '1048576', '');

INSERT INTO g5_content SET co_id = 'company', co_html = '1', co_subject = '회사소개', co_content= '<p align=center><b>회사소개에 대한 내용을 입력하십시오.</b></p>';
INSERT INTO g5_content SET co_id = 'privacy', co_html = '1', co_subject = '개인정보 처리방침', co_content= '<p align=center><b>개인정보 처리방침에 대한 내용을 입력하십시오.</b></p>';
INSERT INTO g5_content SET co_id = 'provision', co_html = '1', co_subject = '서비스 이용약관', co_content= '<p align=center><b>서비스 이용약관에 대한 내용을 입력하십시오.</b></p>';

INSERT INTO g5_faq_master SET fm_id = '1', fm_subject = '자주하시는 질문';

